print ('welcome to the band name generator')
city= input('which city did you grow up in?\n')
print (city)
pet = input('what is the name of your pet?\n')
print (pet)
print ('your band name is ' + city+ '' +pet)
